- name: Bring down Nomad jobs
  hosts: cluster_managers
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.HOME }}:.local/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Bring down Nomad jobs
      when: inventory_hostname == leader_node
      block:
        - name: Bring down services
          command: nmgr down services
          changed_when: true

        - name: Grace period for final writes
          pause:
            seconds: 30

        - name: Bring down infra
          command: nmgr down infra
          changed_when: true

        - name: Grace period for final writes
          pause:
            seconds: 30

- name: Stop jfs mount service
  hosts: all
  become: true
  tasks:
    - name: Stop jfs mount service
      service:
        name: juicefs.service
        state: stopped

- name: Upgrade nodes one at a time
  hosts: all
  serial: 1
  become: true
  vars:
    reboot_timeout: 300
  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: full
        autoremove: true
        purge: true

    - name: Reboot the server
      reboot:
        msg: "Rebooting the server after upgrade"
        reboot_timeout: "{{ reboot_timeout }}"

    - name: Wait for the server to come back online
      wait_for_connection:
        timeout: "{{ reboot_timeout }}"
