- name: Bring down Nomad jobs
  hosts: cluster_managers
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.HOME }}:.local/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Bring down Nomad jobs
      when: inventory_hostname == leader_node
      block:
        - name: Bring down services
          command: nmgr down services
          changed_when: true

        - name: Grace period for final writes
          pause:
            seconds: 60

        - name: Bring down infra
          command: nmgr down infra
          changed_when: true

        - name: Grace period for final writes
          pause:
            seconds: 30

- name: Upgrade nodes one at a time
  hosts: all
  serial: 1
  become: true
  vars:
    reboot_timeout: 300

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: full
        autoremove: true
        purge: true

    - name: Reboot the server
      reboot:
        msg: "Rebooting the server after upgrade"
        reboot_timeout: "{{ reboot_timeout }}"

    - name: Wait for the server to come back online
      wait_for:
        port: "{{ ansible_port }}"
        host: "{{ inventory_hostname }}"
        timeout: "{{ reboot_timeout }}"
        state: started

    - name: Ensure the server is reachable after reboot
      ping:

- name: Restart services
  hosts: all
  become: true
  tasks:
    - name: Restart mount unit
      service:
        name: mnt-nas.mount
        state: restarted
      when: cluster_labels["nas"] != "true"

    - name: Verify nas mount
      find:
        paths: "/mnt/nas"
        recurse: no
        file_type: directory
      register: nas_dirs_found

    - name: Fail on empty mount
      fail:
        msg: "/mnt/nas is empty"
      when: nas_dirs_found.matched < 1

    - name: Restart nomad
      service:
        name: nomad
        state: restarted

    - name: Grace period for Nomad start
      pause:
        seconds: 15
#
- name: Bring up infra jobs
  hosts: cluster_managers
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.HOME }}:.local/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Execute nmgr up infra
      command: nmgr up infra
      changed_when: true
      when: inventory_hostname == leader_node

- name: Bring up jfs mounts
  hosts: all
  become: true
  tasks:
    - name: Grace period for e.g. keydb
      pause:
        seconds: 30

    - name: Restart jfs mount unit
      service:
        name: mnt-jfs.mount
        state: restarted

    - name: Grace period for mount
      pause:
        seconds: 5

    - name: Verify jfs mount
      find:
        paths: "/mnt/jfs"
        recurse: no
        file_type: directory
      register: jfs_dirs_found

    - name: Fail on empty mount
      fail:
        msg: "/mnt/jfs is empty"
      when: jfs_dirs_found.matched < 1

- name: Bring up service jobs
  hosts: cluster_managers
  environment:
    PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.HOME }}:.local/bin:{{ ansible_env.PATH }}"
  tasks:
    - name: Execute nmgr up -d services
      command: nmgr up -d services
      changed_when: true
      when: inventory_hostname == leader_node
