- name: Bring down Nomad jobs
  hosts: cluster_managers
  tasks:
    - name: Execute nmgr down all
      command: nmgr down all
      environment:
        PATH: "{{ ansible_env.HOME }}/bin:{{ ansible_env.HOME }}:.local/bin:{{ ansible_env.PATH }}"
      when: inventory_hostname == leader_node

- name: Upgrade nodes one at a time
  hosts: all
  serial: 1
  become: true
  vars:
    reboot_timeout: 300

  tasks:
    - name: Upgrade all packages to the latest version
      apt:
        update_cache: true
        upgrade: full
        autoremove: true
        purge: true

    - name: Reboot the server
      reboot:
        msg: "Rebooting the server after upgrade"
        reboot_timeout: "{{ reboot_timeout }}"

    - name: Wait for the server to come back online
      wait_for:
        port: "{{ ansible_port }}"
        host: "{{ inventory_hostname }}"
        timeout: "{{ reboot_timeout }}"
        state: started

    - name: Ensure the server is reachable after reboot
      ping:

- name: Restart NAS mount
  hosts: all
  become: true

  tasks:
    - name: Restart mount unit
      service:
        name: mnt-nas.mount
        state: restarted
      when: cluster_labels["nas"] != "true"

    - name: Restart nomad
      service:
        name: nomad
        state: restarted
