- name: Ensure GlusterFS is installed
  apt:
    name:
      - glusterfs-server
      - glusterfs-client
    state: present

- name: Set cluster ip adresses
  set_fact:
    cluster: |
      {% for host in ansible_play_batch -%}
      {{ hostvars[host]['ansible_host'] }}{% if not loop.last %},{% endif %}
      {%- endfor %}
  run_once: true

# Explicit check since if gluster brick already exists, and contains root-owned paths, dir creation below might fail
- name: Check if gluster brick and mount directories exist
  stat:
    path: "{{ item }}"
  loop:
    - "{{ gluster_brick_path }}"
    - "{{ gluster_mount_path }}"
  register: dir_status

- name: Ensure gluster brick and mount directories
  file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ dir_status.results }}"
  when: not item.stat.exists

- name: Enable and start GlusterFS daemon
  systemd:
    name: glusterd
    state: started
    enabled: true

- name: Form a cluster
  command: "gluster peer probe {{ peernode }}"
  loop: "{{ ansible_play_batch | flatten(levels=1) }}"
  loop_control:
    loop_var: peernode
    pause: 2
  register: probe
  run_once: true
  any_errors_fatal: true
  changed_when: "'peer probe: success.' in probe.stdout_lines"

- name: Configure gluster volume
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_path }}"
    replicas: "{{ gluster_replica_count }}"
    cluster: "{{ cluster | trim }}"
    host: "{{ ansible_host }}"
    force: true
    start_on_create: true
    options:
      {
        cache-invalidation-timeout: "600",
        cache-size: "512MB",
        client.event-threads: "8",
        cluster.lookup-optimize: "on",
        features.cache-invalidation: "on",
        group: "metadata-cache",
        nl-cache-positive-entry: "on",
        performance.cache-invalidation: "on",
        performance.cache-max-file-size: "10MB",
        performance.io-cache: "on",
        performance.io-thread-count: "32",
        performance.nl-cache: "on",
        performance.parallel-readdir: "on",
        performance.qr-cache-timeout: "600",
        performance.read-ahead: "on",
        performance.readdir-ahead: "on",
        performance.stat-prefetch: "on",
        performance.write-behind: "on",
        performance.write-behind-window-size: "8MB",
        server.event-threads: "8",
        server.outstanding-rpc-limit: "32",
      }
  run_once: true
