- name: Deploy glusterfs mount service
  template:
    src: glusterfs.mount.j2
    dest: "/etc/systemd/system/home-{{ ansible_user }}-mnt-gluster.mount"
    owner: root
    group: root
    mode: "0644"

- name: Enable glusterfs mount service
  systemd:
    name: "home-{{ ansible_user }}-mnt-gluster.mount"
    enabled: true
    daemon_reload: true
