- name: Set facts
  set_fact:
    jfs_pkg: /tmp/juicefs-ce.tar.gz
    jfs_bin_dir: /usr/local/bin

- name: Get latest release data from GitHub API
  uri:
    url: https://api.github.com/repos/juicedata/juicefs/releases/latest
    return_content: true
  register: release_data

- name: Set latest tag fact
  set_fact:
    latest_tag: "{{ release_data.json.tag_name | regex_replace('^v', '') }}"

- name: Check if juicefs binary exists
  stat:
    path: "{{ jfs_bin_dir }}/juicefs"
  register: juicefs_binary

- name: Get JuiceFS version string
  command: juicefs version
  register: juicefs_version_cmd
  changed_when: false
  when: juicefs_binary.stat.exists

- name: Extract semantic version
  set_fact:
    juicefs_semver: "{{ (juicefs_version_cmd.stdout
      | regex_search('^juicefs version ([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1')
      | first
      | default('0.0.0')) }}"
  when: juicefs_binary.stat.exists

- name: Debug version
  debug:
    msg: "installed: {{ juicefs_semver }}, latest = {{ latest_tag }}"
  when: juicefs_binary.stat.exists and juicefs_version_cmd.rc == 0

- name: Fetch and unarchive JuiceFS binary
  become: true
  unarchive:
    src: "https://github.com/juicedata/juicefs/releases/download/v{{ latest_tag }}/juicefs-{{ latest_tag }}-linux-{{ arch }}.tar.gz"
    dest: "{{ jfs_bin_dir }}"
    remote_src: true
    include:
      - juicefs
  when: not juicefs_binary.stat.exists or (juicefs_semver is version(latest_tag, '<'))
