- name: Install dependencies
  apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker packages
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Enable logrotate for containers
  copy:
    dest: /etc/docker/daemon.json
    content: "{\n  \"log-driver\": \"json-file\",\n  \"log-opts\": {\n    \"max-size\": \"1m\",\n    \"max-file\": \"1\" \n  }\n}\n"

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: true
