cidr_whitelist: "{{ vault_cidr_whitelist.split(' ') }}"
ip_whitelist: "{{ vault_ip_whitelist.split(' ') }}"
collections_list:
  - crowdsecurity/caddy
  - crowdsecurity/dovecot
  - crowdsecurity/iptables
  - crowdsecurity/linux
  - crowdsecurity/postfix
  - crowdsecurity/sshd
parsers_list:
  - crowdsecurity/docker-logs
  - crowdsecurity/whitelists
ban_duration: "duration: 672h"
acquis_addons: |
  ---
  source: journalctl
  journalctl_filter:
    - "_SYSTEMD_UNIT=ssh.service"
  labels:
    type: journald
  ---
  filenames:
    - {{ lookup('env', 'HOME') + '/log/caddy/access.log' }}
  labels:
    type: caddy
  ---
  filenames:
    # - {{ lookup('env', 'HOME') + '/cld/mailserver/data/mail-logs/mail.log' }}
    - /mnt/cld/mailserver/data/mail-logs/mail.log
  labels:
    type: syslog
  ---
