cidr_whitelist: "{{ vault_cidr_whitelist.split(' ') }}"
ip_whitelist: "{{ vault_ip_whitelist.split(' ') }}"
collections_list:
  - crowdsecurity/caddy
  - crowdsecurity/iptables
  - crowdsecurity/linux
  - crowdsecurity/sshd
parsers_list:
  - crowdsecurity/whitelists
ban_duration: "duration: 672h"
acquis_addons: |
  ---
  source: journalctl
  journalctl_filter:
    - "_SYSTEMD_UNIT=ssh.service"
  labels:
    type: journald
  ---
  filenames:
    - {{ ansible_env.HOME }}/log/caddy/access.log
  labels:
    type: caddy
