- name: Set sync folder
  xml:
    path: "{{ syncthing_cfg_file }}"
    xpath: /configuration
    pretty_print: true
    add_children:
      - folder:
          path: "{{ sync_dir }}"
          id: default
          label: Cloud
          rescanIntervalS: "3600"
          fsWatcherEnabled: "true"
          fsWatcherDelayS: "15"
          ignorePerms: "false"
          autoNormalize: "true"

- name: Configure whitelist
  template:
    src: stignore.j2
    dest: "{{ sync_dir }}/.stignore"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600

- name: Configure sync folder
  xml:
    path: "{{ syncthing_cfg_file }}"
    xpath: /configuration/folder[@label="Cloud"]
    pretty_print: true
    add_children:
      - syncOwnership: "true"
      - syncXattrs: "true"
      - copyOwnershipFromParent: "false"

- name: Set GUI on home node
  xml:
    path: "{{ syncthing_cfg_file }}"
    xpath: /configuration/gui/address
    value: "0.0.0.0:8384"
  when: inventory_hostname == leader_node

- name: Disable GUI everywhere else
  xml:
    path: "{{ syncthing_cfg_file }}"
    xpath: /configuration/gui
    attribute: enabled
    value: "false"
  when: inventory_hostname != leader_node

- name: Configure general options
  xml:
    path: "{{ syncthing_cfg_file }}"
    xpath: "/configuration/options/{{ item }}"
    value: "false"
  loop:
    - crashReportingEnabled
    - globalAnnounceEnabled
    - relaysEnabled
    - startBrowser

- name: Collect device ids
  command: /usr/bin/syncthing -device-id
  register: device_id
  become_user: "{{ ansible_user }}"

- name: Remove existing device entries
  xml:
    path: "{{ syncthing_cfg_file }}"
    xpath: /configuration/device
    state: absent

- name: Add devices
  include_tasks: add_device.yml
  loop: "{{ ansible_play_batch }}"
  loop_control:
    loop_var: device_item
  when: device_item != "raspi"

- name: Create an override directory to customize service
  become: true
  file:
    owner: root
    group: root
    mode: 0755
    path: /etc/systemd/system/syncthing@{{ syncthing_user }}.service.d
    state: directory

- name: Grant service extended capabilities for syncOwnership to work
  become: true
  ini_file:
    dest: /etc/systemd/system/syncthing@{{ syncthing_user }}.service.d/override.conf
    owner: root
    group: root
    mode: 0644
    section: Service
    option: AmbientCapabilities
    value: CAP_CHOWN CAP_FOWNER

- name: Start and enable syncthing service
  become: true
  systemd:
    name: syncthing@{{ syncthing_user }}
    state: started
    enabled: true
    daemon_reload: true
  changed_when: false
