- name: Install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - python3-lxml
    state: present

- name: Import syncthing GPG key to apt
  become: true
  get_url:
    url: https://syncthing.net/release-key.txt
    dest: /etc/apt/trusted.gpg.d/syncthing.asc

- name: Add syncthing repository
  become: true
  apt_repository:
    repo: 'deb https://apt.syncthing.net/ syncthing stable'
    state: present

- name: Install syncthing
  become: true
  apt:
    name: syncthing
    state: present
