- name: Ensure rclone plugin default directories
  become: true
  file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: "0755"
  with_items:
    - /var/lib/docker-plugins/rclone/config
    - /var/lib/docker-plugins/rclone/cache

- name: Ensure wanted directories
  file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ lookup('env', 'HOME') + '/.config/rclone' }}"
    - "{{ lookup('env', 'HOME') + '/.cache/rclone/docker' }}"

- name: Clear out previous plugin
  community.docker.docker_plugin:
    plugin_name: rclone/docker-volume-rclone:{{ arch }}
    alias: rclone
    state: absent
    force_remove: true
  become: true

- name: Install rclone docker volume plugin
  become: true
  community.docker.docker_plugin:
    plugin_name: rclone/docker-volume-rclone:{{ arch }}
    alias: rclone
    state: present
    plugin_options:
      config: "{{ lookup('env', 'HOME') + '/.config/rclone' }}"
      cache: "{{ lookup('env', 'HOME') + '/.cache/rclone/docker' }}"
      args: "--allow-other --vfs-cache-mode=full --vfs-cache-max-size=5G"

- name: Enable plugin
  community.docker.docker_plugin:
    plugin_name: rclone/docker-volume-rclone:{{ arch }}
    alias: rclone
    state: enable
