- name: Uninstall old neovim
  apt:
    name: neovim
    state: absent

- name: Install dependencies
  apt:
    pkg:
      - gcc
      - python3-pynvim
      - python3-venv
    update_cache: true

- name: Set Neovim target architecture
  set_fact:
    nvim_arch: >-
      {{ 'x86_64' if ansible_architecture == 'x86_64'
         else 'arm64' if ansible_architecture in ['aarch64', 'arm64']
         else 'unsupported' }}

- name: Fail if unsupported architecture
  fail:
    msg: "Unsupported architecture: {{ ansible_architecture }}"
  when: nvim_arch == 'unsupported'

- name: Download nvim appimage
  get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim-linux-{{ nvim_arch | trim }}.appimage
    dest: /tmp/nvim.appimage
    mode: "0775"

- name: Install nvim
  copy:
    src: /tmp/nvim.appimage
    dest: /usr/local/bin/nvim
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Use nvim alternative
  alternatives:
    name: "{{ item }}"
    path: /usr/local/bin/nvim
  loop:
    - vi
    - vim
    - editor

- name: Sync local nvim config to remotes
  copy:
    src: "{{ ansible_env.HOME }}/.config/nvim"
    dest: "{{ ansible_env.HOME }}/.config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
